# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-6a44db8a-f31a-4f46-acd1-f11ec9adc6ba";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-6a44db8a-f31a-4f46-acd1-f11ec9adc6ba".device =
    "/dev/disk/by-uuid/6a44db8a-f31a-4f46-acd1-f11ec9adc6ba";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D07A-22C5";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-806b4cc4-7897-4086-a1be-62e11675d990"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
